### PR TITLE
Make getUserNickname a public static 

### PR DESCRIPTION
**Pull request by Andrewmob2703-zz**
so that dataservlet can access this.
Also add license lines to this file

### CODE REVIEW

**Review by peizhaoou — COMMENTED** [review]
Which class needs to access it?

**Comment by Andrewmob2703-zz** [comment]
> Which class needs to access it?

DataServlet class

**Comment by peizhaoou** [comment]
Added a related comment in your other PR. You should keep the two in the same PR and even the same commit for changes like this next time because you would want every commit to at least compile and work.

**Review by peizhaoou — APPROVED** [review]

**Comment by Andrewmob2703-zz** [comment]
> Added a related comment in your other PR. You should keep the two in the same PR and even the same commit for changes like this next time because you would want every commit to at least compile and work.

Got it

**Pull request merged**
